name: pkgcheck

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
    - master
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare job
        run: |
          LAST_STATUS=$(gh run list -R ${GITHUB_REPOSITORY} \
            --branch=master \
            --workflow=pkgcheck.yml \
            --status=completed \
            --json=event,conclusion \
            --jq='first(.[] | select(.event != "pull_request")).conclusion'
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --keywords=-RedundantVersion,-NonsolvableDepsInDev
